- name: Create ridecare_backend directory
  file:
    path: /ridecare_backend/target
    state: directory

- name: Copy backend jar file
  copy:
    src: ../ridecare_backend/target/ridecare-0.0.1-SNAPSHOT.jar
    dest: /ridecare_backend/target/ridecare-0.0.1-SNAPSHOT.jar

- name: Copy backend dockerfile
  copy:
    src: ../ridecare_backend/dockerfile
    dest: /ridecare_backend/dockerfile

- name: Build ridecare_backend Dockerfile 
  docker_image:
    name: ridecare_backend_image
    build:
      path: /ridecare_backend/
      args:
        DB_IP: "{{ mysql_ip }}"
        DB_USER: ridecare
        DB_PASSWORD: ridecare
        DB_DATABASE: ridecare_db
        DATALAKE_URL: http://34.105.216.153/datalake/
    source: build
    state: present

- name: Run ridecare_backend
  docker_container:
    name: ridecare_backend_container
    recreate: yes
    published_ports:
      - "80:8080"
    image: ridecare_backend_image


- name: Copy ridecare_backend.sh
  copy:
    src: roles/backend/files/ridecare_backend.sh
    dest: /usr/bin/ridecare_backend.sh

- name: Make it an executable
  shell: sudo chmod +x /usr/bin/ridecare_backend.sh

- name: Copy backendservice.service
  copy:
    src: roles/backend/files/backendservice.service
    dest: /etc/systemd/system/backendservice.service

- name: Give permissions to backendservice.service
  shell: sudo chmod 644 /etc/systemd/system/backendservice.service

- name: Ensure that the service starts whenever the system boots
  shell: sudo systemctl enable backendservice
