- name: Creates directory
  file:
    path: /ridecare_backend/target
    state: directory

- name: Copy jar file
  copy:
    src: ../ridecare_backend/target/ridecare-0.0.1-SNAPSHOT.jar
    dest: /ridecare_backend/target/ridecare-0.0.1-SNAPSHOT.jar

- name: Copy dockerfile
  copy:
    src: ../ridecare_backend/dockerfile
    dest: /ridecare_backend/dockerfile

- name: Copy docker-compose file
  copy:
    src: ../ridecare_backend/docker-compose.yml
    dest: /ridecare_backend/docker-compose.yml

- name: Run docker-compose
  docker_compose:
    project_src: /ridecare_backend
    files:
      - "docker-compose.yml"
    state: present