- name: Creates directory
  file:
    path: /ridecare_backend/target
    state: directory

- name: Copy jar file
  copy:
    src: ../ridecare_backend/target/ridecare-0.0.1-SNAPSHOT.jar
    dest: /ridecare_backend/target/ridecare-0.0.1-SNAPSHOT.jar

- name: Copy dockerfile
  copy:
    src: ../ridecare_backend/dockerfile
    dest: /ridecare_backend/dockerfile

- name: Copy docker-compose file
  copy:
    src: ../ridecare_backend/docker-compose.yml
    dest: /ridecare_backend/docker-compose.yml

- name: Run docker-compose
  docker_compose:
    project_src: /ridecare_backend
    files:
      - "docker-compose.yml"
    state: present

- name: Copy ridecare_backend.sh
  copy:
    src: ridecare_backend.sh
    dest: /usr/bin/ridecare_backend.sh

- name: Make it an executable
  shell: sudo chmod +x /usr/bin/ridecare_backend.sh

- name: Copy backendservice.service
  copy:
    src: backendservice.service
    dest: /etc/systemd/system/backendservice.service

- name: Give permissions to backendservice.service
  shell: sudo chmod 644 /etc/systemd/system/backendservice.service

- name: Ensure that the service starts whenever the system boots
  shell: sudo systemctl enable backendservice