version: '2.1'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VUE_APP_ROOT_API: http://localhost:8080
    container_name: ridecare_frontend
    ports:
      - 3000:80

