version: '2.1'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend_mysql


networks:
  backend_mysql:
    external: true