- name: Copy ridecare_frontend directory
  copy:
    src: ../ridecare_frontend
    dest: /

- name: Build ridecare_frontend Dockerfile 
  docker_image:
    name: ridecare_frontend_image
    build:
      path: /ridecare_frontend/
      args:
        VUE_APP_ROOT_API: "http://{{ backend_ip }}:{{backend_port}}"
    source: build     
    state: present

- name: Run ridecare_frontend
  docker_container:
    name: ridecare_frontend_container
    recreate: yes
    published_ports:   
      - "3000:80"
    image: ridecare_frontend_image
