---

- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: gcp
      vars:
        gcp_zone: us-west1-b
        gcp_region: us-west1
        gcp_project:  gentle-ally-299814
        gcp_cred_kind: serviceaccount
        gcp_cred_file: credentials.json
        gcp_machine_type: e2-medium
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20210105
        disk_size: 20
        disks:
          - disk-01
          - disk-02
          - disk-03
          - disk-04
          - disk-05
        addresses:
          - addr-01
          - addr-02
          - addr-03
          - addr-04
          - addr-05
        instances:
          - { index: 1, tag: backend-mysql, name: backend-mysql } 
          - { index: 2, tag: backend1, name: backend1 } 
          - { index: 3, tag: backend2, name: backend2 } 
          - { index: 4, tag: backend-nginx, name: backend-nginx } 
          - { index: 5, tag: frontend, name: frontend } 


- hosts: all
  become: yes
  roles:
    - { role: users, payload: users.yml }
    - { role: docker }

- hosts: backend-mysql
  gather_facts: yes
  become: yes
  roles:
    - role: mysql

- hosts: backend1
  gather_facts: yes
  become: yes
  roles:
    - {
      role: backend,
      mysql_ip: "{{ groups['backend-mysql'][0] }}"
      }

- hosts: backend2
  gather_facts: yes
  become: yes
  roles:
    - {
      role: backend,
      mysql_ip: "{{ groups['backend-mysql'][0] }}"
      }

- hosts: backend-nginx
  gather_facts: yes
  become: yes
  roles:
    - {
      role: nginx,
      backend1_ip: "{{ groups['backend1'][0] }}",
      backend2_ip: "{{ groups['backend2'][0] }}"
      }

- hosts: frontend
  gather_facts: yes
  become: yes
  roles:
    - {
      role: frontend,
      backend_ip: "{{ groups['backend-nginx'][0] }}",
      backend_port: "80"
      }