---

- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: gcp
      vars:
        gcp_zone: us-west1-b
        gcp_region: us-west1
        gcp_project:  gentle-ally-299814
        gcp_cred_kind: serviceaccount
        gcp_cred_file: credentials.json
        gcp_machine_type: e2-medium
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20210105
        disk_size: 20
        disks:
          - disk-01
          - disk-02
        addresses:
          - addr-01
          - addr-02
        instances:
          - { index: 1, tag: backend, name: backend } 
          - { index: 2, tag: frontend, name: frontend } 


- hosts: all
  become: yes
  roles:
    - { role: users, payload: users.yml }
    - { role: docker }


- hosts: backend
  gather_facts: yes
  become: yes
  roles:
    - role: backend

- hosts: frontend
  gather_facts: yes
  become: yes
  roles:
    - {
      role: frontend,
      backend_ip: "{{ hostvars[groups['backend'][0]]['ansible_%s' | format(ansible_interfaces[0])].ipv4.address }}",
      backend_port: ":8080"
      }