version: '2.1'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ridecare
      MYSQL_PASSWORD: ridecare
      MYSQL_DATABASE: ridecare_db
    volumes:
      - "./databaseScripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./databaseScripts/init.sql:/docker-entrypoint-initdb.d/2.sql"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend1:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DB_IP: mysql
      DB_USER: ridecare
      DB_PASSWORD: ridecare
      DB_DATABASE: ridecare_db
      DATALAKE_URL: http://34.105.216.153/datalake/
    container_name: backend1
    ports:
      - 8081:8080
    depends_on:
      mysql:
        condition: service_healthy

  backend2:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DB_IP: mysql
      DB_USER: ridecare
      DB_PASSWORD: ridecare
      DB_DATABASE: ridecare_db
      DATALAKE_URL: http://34.105.216.153/datalake/
    container_name: backend2
    ports:
      - 8082:8080
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8080:9090
    depends_on:
      - backend1
      - backend2


