version: '2.1'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ridecare
      MYSQL_PASSWORD: ridecare
      MYSQL_DATABASE: ridecare_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  spring_boot:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DB_USER: ridecare
      DB_PASSWORD: ridecare
      DB_DATABASE: ridecare_db
    container_name: ridecare_backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080

