version: '2.1'
services:
  backend1:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DB_IP: mysql
      DB_USER: ridecare
      DB_PASSWORD: ridecare
      DB_DATABASE: ridecare_db
      DATALAKE_URL: http://34.105.216.153/datalake/
    container_name: backend1
    networks:
      - backend_network
    ports:
      - 8081:8080

  backend2:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DB_IP: mysql
      DB_USER: ridecare
      DB_PASSWORD: ridecare
      DB_DATABASE: ridecare_db
      DATALAKE_URL: http://34.105.216.153/datalake/
    container_name: backend2
    networks:
      - backend_network
    ports:
      - 8082:8080

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8080:9090
    networks:
      - backend_network
    depends_on:
      - backend1
      - backend2

networks:
  backend_network:
    external: true

