version: '2.1'
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      DB_IP: mysql
      DB_USER: ridecare
      DB_PASSWORD: ridecare
      DB_DATABASE: ridecare_db
      DATALAKE_URL: http://34.105.216.153/datalake/
    container_name: backend
    ports:
      - 80:8080

