---

- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: gcp
      vars:
        gcp_zone: us-west1-b
        gcp_region: us-west1
        gcp_project:  gentle-ally-299814
        gcp_cred_kind: serviceaccount
        gcp_cred_file: credentials.json
        gcp_machine_type: e2-medium
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20210105
        disk_size: 20
        disks:
          - disk-01
        addresses:
          - addr-01
        instances:
          - { index: 1, tag: backend, name: backend } 


- hosts: all
  become: yes
  roles:
    - { role: users, payload: users.yml }
    - { role: docker }


- hosts: backend
  gather_facts: yes
  become: yes
  roles:
    - role: backend