version: '2.1'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    networks:
      - backend_mysql
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ridecare
      MYSQL_PASSWORD: ridecare
      MYSQL_DATABASE: ridecare_db
    
networks:
    backend_mysql:
        external: true