version: "3"

services:
    mysql_slave:
        image: robinong79/mysql_repl:5.7 
        ports:
            - "3308:3306"
        networks:
            - mysqlcluster
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=ridecare
            - MYSQL_PASSWORD=ridecare
            - MYSQL_DATABASE=ridecare_db
            - SERVER_ID=2
            - BIND_ADDRESS=0.0.0.0
            - AUTO_INIT_MASTER_IP=mysql_master
        volumes:
            - /var/dockerdata/mysqlcluster/mysql02/lib:/var/lib/mysql
            - /var/dockerdata/mysqlcluster/mysql02/conf.d:/etc/mysql/conf.d
            - /var/dockerdata/mysqlcluster/mysql02/log:/var/log/mysql
            - /var/dockerdata/mysqlcluster/mysql02/initdb.d:/docker-entrypoint-initdb.d
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 60s
            restart_policy:
                condition: on-failure
                max_attempts: 5
            placement:
                constraints: [node.role == worker]
    
networks:
    mysqlcluster:
        external: true

