- name: Create MySql directory
  file:
    path: /mysql
    state: directory

- name: Create Scripts directory to store initialization files
  file:
    path: /mysql/scripts
    state: directory

- name: Copy MySql docker-compose file
  copy:
    src: roles/mysql/files/docker-compose.yml
    dest: /mysql/docker-compose.yml

- name: Copy script files (init.sql and schema.sql)
  copy:
    src: roles/mysql/files/scripts/{{item}}
    dest: /mysql/scripts/{{item}}
  loop:
    - init.sql
    - schema.sql

- name: Pull mysql docker latest image
  docker_image:
    name: mysql:latest
    source: pull
  
- name: Create network for communication between containers
  docker_network:
    name: backend_network
    driver: bridge

- name: Run MySql docker-compose
  docker_compose:
    project_src: /mysql
    files:
      - "docker-compose.yml"
    state: present
